### ISSUE TITLE
LEDSliderGreenHandle.svg is used without permission or attribution

### ISSUE THREAD

**Issue by falkTX** [algoritmarte/AlgoritmarteVCVPlugin#2]
Hi there.
Just noticed for the `v2` branch you imported the `LEDSliderGreenHandle.svg` file from VCV Rack per aa2f6ffb96b4d6a0c3e9d67188d4a6b8bbdbef74.

There are very specific restrictions on the use of these files, as per [Rack's README from v1](https://github.com/VCVRack/Rack/blob/v1/LICENSE.md).

> The Component Library graphics for Rack are copyright © 2019 [VCV](https://vcvrack.com/) and licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/). Non-commercial use is allowed with appropriate credit and indication of the original license.

Please provide the necessary attribution for this and any other files you might have copied.
Thanks!

**Comment by algoritmarte** [comment]
Attribution added:

https://github.com/algoritmarte/AlgoritmarteVCVPlugin/blob/v2/res/LICENSE.md

**Comment by falkTX** [comment]
That was quick, thanks a lot!
